	.xlist
;
;------------------------------------------------------------------------------
;
; Conditional assembly switch
HYBRID			equ	-1	;DOS1/DOS2 hybrid system
STURBO			equ	-1	;support super turbo mode (for MSXturboR)
BUILTIN			equ	-1	;built-in system
RC2014			equ	0	; SWITCH TO CONTROL FEATURES SPECIFIC TO RC2014
;
;-----------------------------------------------------------------------------
;
	.list
;
